import { createContext, useContext, useState } from 'react';

const translations = {
  sq: {
    home: 'Kryefaqja',
    menu: 'Menu',
    cart: 'Shporta',
    viewMenu: 'Shiko Menunë',
    welcome: 'Mirë se vini në faqen tonë zyrtare! Shijoni bukën dhe picat më të mira në qytet.',
    bakery: 'Furra & Piceria Europa',
    about: 'Rreth Nesh',
    aboutText: 'Jemi një furrë dhe piceri familjare me traditë, që ofrojmë produkte të freskëta çdo ditë. Përdorim përbërës cilësorë dhe recetat më të mira për të kënaqur çdo shije.',
    menuSectionTitle: 'Menuja jonë',
    menuSectionDesc: 'Zgjidh kategorinë tënde të preferuar!',
    menuCardBread: 'Bukë të freskëta',
    menuCardBreadDesc: 'Bukë tradicionale, e pjekur çdo ditë.',
    menuCardBurek: 'Burek të ngrohtë',
    menuCardBurekDesc: 'Burek me mish, djath ose spinaq.',
    menuCardPizza: 'Pizza italiane',
    menuCardPizzaDesc: 'Pizza me recetë tradicionale.',
    menuCardBtn: 'Shiko menunë',
    featuredProductsTitle: 'Produktet më të porositura',
    featuredProductsDesc: 'Zgjedhjet më të preferuara nga klientët tanë, gati për t\'i parë në menu.',
    menuPageTitle: 'Menu',
    menuPageSub: 'Përzgjidh sipas shijes tuaj ose gjej ushqimin tënd të parapëlqyer!',
    filterByCategory: 'Filtro sipas kategorisë:',
    allCategories: 'Të gjitha',
    addToCart: 'Shto në shportë',
    addShort: 'Shto',
    cartTitle: 'Shporta',
    cartEmpty: 'Shporta është bosh.',
    remove: 'Hiq',
    total: 'Totali',
    sendWhatsapp: 'Dërgo në WhatsApp',
    sendSMS: 'Dërgo me SMS',
    orderFromWeb: 'Porosi nga Web',
    notFound: 'Faqja nuk u gjet!',
    testimonialSection: 'Çfarë thonë klientët tanë',
    contact: 'Kontakt',
    contactText: 'Na kontaktoni në WhatsApp: {phone}\nOse na vizitoni në lokacionin tonë për të provuar produktet tona të freskëta.',
    menuPageFilter: 'Filtro sipas kategorisë:',
    testimonial1: 'Shërbimi ishte i shkëlqyer dhe ushqimi shumë i shijshëm!',
    testimonial2: 'Ambienti shumë i ngrohtë dhe stafi shumë mikpritës.',
    testimonial3: 'Produktet janë gjithmonë të freskëta dhe të shijshme!',
    address: 'Adresa',
    email: 'Email',
    phone: 'Tel/WhatsApp/Viber',
    followUs: 'Na ndiqni:',
    openMap: 'Hape në Google Maps',
    mapLocationTitle: 'Lokacioni ynë',
  },
  en: {
    home: 'Home',
    menu: 'Menu',
    cart: 'Cart',
    viewMenu: 'View Menu',
    welcome: 'Welcome to our official page! Enjoy the best bread and pizza in town.',
    bakery: 'Europa Bakery & Pizzeria',
    about: 'About Us',
    aboutText: 'We are a family bakery and pizzeria with tradition, offering fresh products every day. We use quality ingredients and the best recipes to satisfy every taste.',
    menuSectionTitle: 'Our Menu',
    menuSectionDesc: 'Choose your favorite category!',
    menuCardBread: 'Fresh Bread',
    menuCardBreadDesc: 'Traditional bread, baked daily.',
    menuCardBurek: 'Warm Burek',
    menuCardBurekDesc: 'Burek with meat, cheese or spinach.',
    menuCardPizza: 'Italian Pizza',
    menuCardPizzaDesc: 'Pizza with a traditional recipe.',
    menuCardBtn: 'View Menu',
    featuredProductsTitle: 'Most Ordered Products',
    featuredProductsDesc: 'The customer favorites you will most likely want to order first.',
    menuPageTitle: 'Menu',
    menuPageSub: 'Choose by your taste or find your favorite food!',
    filterByCategory: 'Filter by category:',
    allCategories: 'All',
    addToCart: 'Add to cart',
    addShort: 'Add',
    cartTitle: 'Cart',
    cartEmpty: 'Cart is empty.',
    remove: 'Remove',
    total: 'Total',
    sendWhatsapp: 'Send on WhatsApp',
    sendSMS: 'Send by SMS',
    orderFromWeb: 'Order from Web',
    notFound: 'Page not found!',
    testimonialSection: 'What our clients say',
    contact: 'Contact',
    contactText: 'Contact us on WhatsApp: {phone}\nOr visit us at our location to try our fresh products.',
    menuPageFilter: 'Filter by category:',
    testimonial1: 'The service was excellent and the food very tasty!',
    testimonial2: 'Very warm environment and very welcoming staff.',
    testimonial3: 'Products are always fresh and delicious!',
    address: 'Address',
    email: 'Email',
    phone: 'Phone/WhatsApp/Viber',
    followUs: 'Follow us:',
    openMap: 'Open in Google Maps',
    mapLocationTitle: 'Our location',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('sq');
  const t = (key) => translations[lang][key] || key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
